#pragma once

#include "../lang/cs.h"

CUTSCENE(Intro)

	$TEXTURE(slide0)	$ENTITY(entSlide0)
	$TEXTURE(slide1)	$ENTITY(entSlide1)
	$TEXTURE(slide2)	$ENTITY(entSlide2)
	$TEXTURE(slide3)	$ENTITY(entSlide3)
	$TEXTURE(slide4)	$ENTITY(entSlide4)
	$TEXTURE(slide5)	$ENTITY(entSlide5)
	$TEXTURE(slide6)	$ENTITY(entSlide6)
	$TEXTURE(slide7)	$ENTITY(entSlide7)
	$TEXTURE(slide8)	$ENTITY(entSlide8)
	$TEXTURE(slide9)	$ENTITY(entSlide9)
	$TEXTURE(slide10)	$ENTITY(entSlide10)
	$TEXTURE(slide11)	$ENTITY(entSlide11)
	$TEXTURE(slide12)	$ENTITY(entSlide12)
	$TEXTURE(slide13)	$ENTITY(entSlide13)
	$TEXTURE(slide14)	$ENTITY(entSlide14)
	$TEXTURE(slide15)	$ENTITY(entSlide15)
	/* Blank */			$ENTITY(entSlide16)

	$$CONSTRUCT
		$$TEXTURE(slide0, "resources/textures/Intro/Slide0.png")	$$SIMPLE_ENTITY(entSlide0, "slide0", 0, slide0, 0, 0)
		$$TEXTURE(slide1, "resources/textures/Intro/Slide1.png")	$$SIMPLE_ENTITY(entSlide1, "slide1", 1, slide1, 0, 0)
		$$TEXTURE(slide2, "resources/textures/Intro/Slide2.png")	$$SIMPLE_ENTITY(entSlide2, "slide2", 2, slide2, 0, 0)
		$$TEXTURE(slide3, "resources/textures/Intro/Slide3.png")	$$SIMPLE_ENTITY(entSlide3, "slide3", 3, slide3, 0, 0)
		$$TEXTURE(slide4, "resources/textures/Intro/Slide4.png")	$$SIMPLE_ENTITY(entSlide4, "slide4", 4, slide4, 0, 0)
		$$TEXTURE(slide5, "resources/textures/Intro/Slide5.png")	$$SIMPLE_ENTITY(entSlide5, "slide5", 5, slide5, 0, 0)
		$$TEXTURE(slide6, "resources/textures/Intro/Slide6.png")	$$SIMPLE_ENTITY(entSlide6, "slide6", 6, slide6, 0, 0)
		$$TEXTURE(slide7, "resources/textures/Intro/Slide7.png")	$$SIMPLE_ENTITY(entSlide7, "slide7", 7, slide7, 0, 0)
		$$TEXTURE(slide8, "resources/textures/Intro/Slide8.png")	$$SIMPLE_ENTITY(entSlide8, "slide8", 8, slide8, 0, 0)
		$$TEXTURE(slide9, "resources/textures/Intro/Slide9.png")	$$SIMPLE_ENTITY(entSlide9, "slide9", 9, slide9, 0, 0)
		$$TEXTURE(slide10, "resources/textures/Intro/Slide10.png")	$$SIMPLE_ENTITY(entSlide10, "slide10", 10, slide10, 0, 0)
		$$TEXTURE(slide11, "resources/textures/Intro/Slide11.png")	$$SIMPLE_ENTITY(entSlide11, "slide11", 11, slide11, 0, 0)
		$$TEXTURE(slide12, "resources/textures/Intro/Slide12.png")	$$SIMPLE_ENTITY(entSlide12, "slide12", 12, slide12, 0, 0)
		$$TEXTURE(slide13, "resources/textures/Intro/Slide13.png")	$$SIMPLE_ENTITY(entSlide13, "slide13", 13, slide13, 0, 0)
		$$TEXTURE(slide14, "resources/textures/Intro/Slide14.png")	$$SIMPLE_ENTITY(entSlide14, "slide14", 14, slide14, 0, 0)
		$$TEXTURE(slide15, "resources/textures/Intro/Slide15.png")	$$SIMPLE_ENTITY(entSlide15, "slide15", 15, slide15, 0, 0)
		/* blank */													$$SIMPLE_ENTITY(entSlide16, "slide16", 16, slide0, 0, 0)
	x$$CONSTRUCT

	MAIN
		TEXT("Officer: OK, shall we start! Give me a sec for setting up.")
		ADD_ENTITY(entSlide0)
		TEXT("Officer: Who the heck put an anime girl onto the projector machine? Get this travesty of the screen!")
		ADD_ENTITY(entSlide1)
		TEXT("Officer: OK! It's now gone. Let's discuss about the mission! That garbage is off the screen!")
		TEXT("Officer #2: And that coming from a guy using Comic Sans Serif!")
		TEXT("Officer: Shut up! We have a national security matter here! Let's get it done quickly! You know Ms. President has been kidnap and we need to brief this person ASAP!")
		ADD_ENTITY(entSlide2)
		TEXT("Officer: BACKGROUND INFORMATION!")
		TEXT("Officer: The current president, Ms. Regina Raffleson, has been kidnapped by an organization named the Elite Four.")
		TEXT("Officer: The Elite Four has the following members: Crocobirdo, Pyrite the Hedgehoge, Vug, YOLO Bear")
		ADD_ENTITY(entSlide3)
		TEXT("Officer: THE VICTIM - MS. PRESIDENT!")
		TEXT("Officer: She is the daughter of the former president.Comes in the power around 18 Aug 2055.")
		TEXT("Officer: She has a unique mutation: her hair is pink. She is the only known human on Earth whose hair is naturally pink.")
		ADD_ENTITY(entSlide4)
		TEXT("Officer: CROCOBIRDO!")
		TEXT("Officer: Here is the picture:")
		ADD_ENTITY(entSlide5)
		TEXT("Officer: Crocobirdo is \"The King of All Crocodiles and the King of All Birds.\"")
		TEXT("Officer: Immensely powerful. Very difficult to defeat.")
		TEXT("Officer: Believed to be an ancient hero.")
		ADD_ENTITY(entSlide6)
		TEXT("Officer: PYRITE THE HEDGEHOGE!")
		TEXT("Officer: Here is the picture:")
		ADD_ENTITY(entSlide7)
		TEXT("Officer: He is the last member of the hedgehoge species.")
		TEXT("Officer: He's supposed to be the fastest thing alive.")
		TEXT("Officer: Has a crush on Ms. President. This is probably the reason why he joins the Elite Four.")
		TEXT("Officer: His booger is probably radioactive.")
		ADD_ENTITY(entSlide8)
		TEXT("Officer: VUG!")
		TEXT("Officer: Here is the picture:")
		ADD_ENTITY(entSlide9)
		TEXT("Officer: Was probably a human who has done a terrible thing to Ms. President and is seeking a revenge.")
		TEXT("Officer: Can shapeshift. A very tricky foe.")
		TEXT("Officer: Currently, it is hiding amongst other humans. Quickly seek it out for the welfare of the others!")
		ADD_ENTITY(entSlide10)
		TEXT("Officer: YOLO Bear!")
		TEXT("Officer: Here is the picture:")
		ADD_ENTITY(entSlide11)
		TEXT("Officer: Despite of his shape, he is a pick-up artist.")
		TEXT("Officer: Unlike other Elite Four, lives openly with the others.")
		TEXT("Officer: Despite can be sought out easily, very hard to catch since he is very magical.")
		ADD_ENTITY(entSlide12)
		TEXT("Officer: DARK PREMIER, The Evil Premier Who Is Behind Everything.")
		ADD_ENTITY(entSlide13)
		TEXT("Officer: The final boss!")
		TEXT("Officer: He used to be the prime minister under Ms. President. Then he betrayed her!")
		TEXT("Officer: We never saw him before, so no pics.. sorry.")
		ADD_ENTITY(entSlide14)
		TEXT("Officer: ATTACK PLAN!")
		TEXT("Officer: Ms.President is currently held in Dark Premier's Castle of Darkness. The main door can only with 4 keys. The keys can be found on the Elite Four.")
		TEXT("Officer: So, take down the Elite Four to take the key and then take on the Dark Premier. Then you will have rescued Ms. President.")
		ADD_ENTITY(entSlide15)
		TEXT("Officer: Are you bad enough to rescue the president?")
		TEXT("Officer: OK. The presentation is over. Now go rescue Ms. President!")
		ADD_ENTITY(entSlide16)
		TEXT("Officer #2: That was a sucky presentation. You are reading off the slide!")
	xMAIN
xCUTSCENE